name       : epson-inkjet-printer-escpr
version    : 1.7.22
release    : 12
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/13/96/55/c6fced63098ae1ba104f11f572794fd558ffca29/epson-inkjet-printer-escpr-1.7.22-1lsb3.2.tar.gz : 0b2fefa7fd077b6fdf778cb53a8c60bf999a396ef88145182c5c4a08f34c652c
homepage   : http://download.ebz.epson.net/dsc/search/01/search/?OSC=LX
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Common Linux printer driver for Epson Multifunction Inkjet Printers.
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
