name       : epson-inkjet-printer-escpr
version    : 1.6.20
release    : 5
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/07/16/23/804253d188a31ae6a0f2722648248ef952afedfb/epson-inkjet-printer-escpr-1.6.20-1lsb3.2.tar.gz : e09c08ac79e58076f1f5bd0528f2249e8eda4eab3226afd76f6fad79e80500a5
license    : GPL-2.0
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
