name       : epson-inkjet-printer-escpr
version    : 1.6.23
release    : 6
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/07/72/04/eb05a9e15ed0bc8b0949e9dd220f144d3efec288/epson-inkjet-printer-escpr-1.6.23-1lsb3.2.tar.gz : ef6c7a46394dca72edd052c612c22f133429d8452b8b5fbbd3896da30424fa20
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
