name       : epson-inkjet-printer-escpr
version    : 1.6.17
release    : 4
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/06/66/09/4ac2bf69bb1ddf4a9ad525596615cbb40fe4dad5/epson-inkjet-printer-escpr-1.6.17-1lsb3.2.tar.gz : 9b2e5cd1b7b232d4404b78a3ec0a0d5aa70dba860c73ef641199f0ad1a0fdb54
license    : GPL-2.0
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
