name       : epson-inkjet-printer-escpr
version    : 1.7.10
release    : 8
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/12/68/34/82ca3e84f17410b5ec6818e5698524b1f42862cb/epson-inkjet-printer-escpr-1.7.10-1lsb3.2.tar.gz : 0f98b55fe971a7ede36a5f71139ba8020d6dbf3a7c9b309a1a4fc4f50ae26148
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
