name       : epson-inkjet-printer-escpr
version    : 1.7.26
release    : 13
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/14/48/15/c864d000b06bebeec8832ce6f68bb079c36d838a/epson-inkjet-printer-escpr-1.7.26-1lsb3.2.tar.gz : 690e8c9c5b993489830de5ddb16ba2ba4c21b474978bda082ed7d1d1c48482e9
homepage   : http://download.ebz.epson.net/dsc/search/01/search/?OSC=LX
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Common Linux printer driver for Epson Multifunction Inkjet Printers.
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
