name       : epson-inkjet-printer-escpr
version    : 1.6.13
release    : 3
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/05/55/39/d16f39e5f8953e033f6f38083b38c50c543b891c/epson-inkjet-printer-escpr-1.6.13-1lsb3.2.tar.gz : 6b17bbd9de8b2e2541e90cdcdd6272bae4922f51898aa8e72f0a8e8378aad81d
license    : GPL-2.0
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
