name       : epson-inkjet-printer-escpr
version    : 1.6.5
release    : 2
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/04/54/27/b73564748bfde7b7ce625e20d4a3257d447bec79/epson-inkjet-printer-escpr-1.6.5-1lsb3.2.tar.gz : 1cd9e0506bf181e1476bd8305f1c6b8dbc4354eab9415d0d5529850856129e4c
license    : GPL-2.0
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
