name       : epson-inkjet-printer-escpr
version    : 1.7.17
release    : 11
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/12/99/78/73605b3f8aac63694fdabee6bd43389731696cd9/epson-inkjet-printer-escpr-1.7.17-1lsb3.2.tar.gz : 8f13f5344f50399bd49e8871b84bd379e9f2957d97f47a044449f959689eecb4
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
