name       : epson-inkjet-printer-escpr
version    : 1.7.4
release    : 7
source     :
    - https://download3.ebz.epson.net/dsc/f/03/00/10/19/83/de1d4c8152d80dc3afd14512e6b4e8ebd683ffc4/epson-inkjet-printer-escpr-1.7.4-1lsb3.2.tar.gz : da4ea460ef6c82c0daa22666f96ceb5a7511397f8ce0e2803bebd098305ac384
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Printer drivers for Epson printers
libsplit   : no
description: |
    Printer drivers for Epson printers
builddeps  :
    - cups-devel
rundeps    :
    - cups
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
